/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import Link from "next/link";
import AdminShell from "@/app/components/admin/AdminShell";
import { requireAdmin } from "@/app/lib/supabase/admin-session";
import { listApplications } from "@/app/lib/programs/queries";
export const metadata: Metadata = { robots: { index: false, follow: false } }; export const dynamic = "force-dynamic";
const tile = (label:string,value:string|number) => <div className="border border-[#1a1816]/10 bg-white px-5 py-4"><p className="text-2xl font-light">{value}</p><p className="mt-1 text-xs uppercase tracking-widest text-[#1a1816]/50">{label}</p></div>;
export default async function Page() { await requireAdmin(); const apps = await listApplications(); const invited=apps.filter(a=>a.status==="INVITED"||a.status==="BOOKED").length, review=apps.filter(a=>a.status==="UNDER_REVIEW").length, declined=apps.filter(a=>a.status==="NOT_FIT"||a.status==="DECLINED").length, booked=apps.filter(a=>a.status==="BOOKED").length; return <AdminShell><p className="text-xs uppercase tracking-widest text-[#1a1816]/45">Programs</p><h1 className="mt-2 text-3xl font-light">Corporate Transition</h1><div className="my-8 grid grid-cols-2 gap-4 md:grid-cols-5">{tile("Applications",apps.length)}{tile("Invited",invited)}{tile("Under review",review)}{tile("Declined / not fit",declined)}{tile("Booked",booked)}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-[#1a1816]/15 text-left text-xs uppercase tracking-widest text-[#1a1816]/50"><th className="py-3">Applicant</th><th>Applied</th><th>Route</th><th>Status</th><th>Booking</th><th></th></tr></thead><tbody>{apps.map((a:any)=><tr key={a.id} className="border-b border-[#1a1816]/10"><td className="py-4">{a.answers.firstName} {a.answers.lastName}</td><td>{new Date(a.submitted_at).toLocaleDateString()}</td><td>{a.ai_route}</td><td>{a.status.replaceAll("_"," ")}</td><td>{a.booking_status.replaceAll("_"," ")}</td><td><Link className="text-[#6b1f1f] underline" href={`/admin/programs/corporate-transition/${a.id}`}>Review →</Link></td></tr>)}</tbody></table>{!apps.length&&<p className="py-10 text-[#1a1816]/50">No applications yet.</p>}</div></AdminShell>; }
